name: LCK Schedule Auto Update

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # v4 대신 v5 이상 버전 사용 (Node 24 호환)
      - uses: actions/checkout@v5 
      
      # v5 대신 v6 이상 버전 사용
      - name: 파이썬 설정
        uses: actions/setup-python@v6 
        with:
          python-version: '3.12'

      - name: 라이브러리 설치
        run: pip install -r requirements.txt

      - name: 크롤러 실행
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python lck_crawler.py
